-- proc>flow v2.1.0 — DB2 ERD sample (8 tables, 4 views).
-- Tables EMPLOYEE (2) and ORDERS (4) are related through the employee who
-- took the order. AUDIT_LOG and APP_SETTINGS are standalone: nothing
-- references them and they reference nothing.
-- Every relationship below is a declared FOREIGN KEY.

CREATE SCHEMA sales;

CREATE TABLE sales.department (
  dept_id      INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 10),
  dept_name    VARCHAR(80)   NOT NULL,
  location     VARCHAR(80),
  CONSTRAINT pk_department PRIMARY KEY (dept_id),
  CONSTRAINT uq_department_name UNIQUE (dept_name)
);

CREATE TABLE sales.employee (
  emp_id       INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  dept_id      INTEGER       NOT NULL,
  manager_id   INTEGER,
  full_name    CHARACTER VARYING(120) NOT NULL,
  hired_on     DATE          NOT NULL DEFAULT CURRENT DATE,
  salary       DECIMAL(11,2) NOT NULL,
  CONSTRAINT pk_employee PRIMARY KEY (emp_id),
  CONSTRAINT fk_employee_dept FOREIGN KEY (dept_id)
    REFERENCES sales.department (dept_id) ON DELETE RESTRICT,
  CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id)
    REFERENCES sales.employee (emp_id) ON DELETE SET NULL
);

CREATE TABLE sales.customer (
  customer_id  INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,
  customer_name VARCHAR(120) NOT NULL,
  email        VARCHAR(200)  NOT NULL,
  country      CHAR(2),
  CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);

CREATE TABLE sales.orders (
  order_id     INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,
  customer_id  INTEGER       NOT NULL,
  emp_id       INTEGER       NOT NULL,
  order_date   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  status       VARCHAR(20)   NOT NULL,
  CONSTRAINT pk_orders PRIMARY KEY (order_id),
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)
    REFERENCES sales.customer (customer_id) ON DELETE CASCADE,
  CONSTRAINT fk_orders_employee FOREIGN KEY (emp_id)
    REFERENCES sales.employee (emp_id) ON DELETE RESTRICT,
  CONSTRAINT ck_orders_status CHECK (status IN ('OPEN','SHIPPED','CANCELLED'))
);

CREATE TABLE sales.product (
  product_id   INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,
  sku          VARCHAR(40)   NOT NULL,
  product_name VARCHAR(160)  NOT NULL,
  unit_price   DECIMAL(9,2)  NOT NULL,
  CONSTRAINT pk_product PRIMARY KEY (product_id)
);
CREATE UNIQUE INDEX sales.uq_product_sku ON sales.product (sku);

CREATE TABLE sales.order_line (
  order_id     INTEGER       NOT NULL,
  line_no      SMALLINT      NOT NULL,
  product_id   INTEGER       NOT NULL,
  quantity     INTEGER       NOT NULL,
  unit_price   DECIMAL(9,2)  NOT NULL,
  CONSTRAINT pk_order_line PRIMARY KEY (order_id, line_no),
  CONSTRAINT fk_order_line_order FOREIGN KEY (order_id)
    REFERENCES sales.orders (order_id) ON DELETE CASCADE,
  CONSTRAINT fk_order_line_product FOREIGN KEY (product_id)
    REFERENCES sales.product (product_id) ON DELETE RESTRICT
);

-- Standalone table 7: audit trail, no foreign keys in or out.
CREATE TABLE sales.audit_log (
  log_id       BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY,
  message      VARCHAR(500)  NOT NULL,
  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
  CONSTRAINT pk_audit_log PRIMARY KEY (log_id)
);

-- Standalone table 8: application settings, no foreign keys in or out.
CREATE TABLE sales.app_settings (
  setting_key   VARCHAR(100) NOT NULL,
  setting_value VARCHAR(500),
  CONSTRAINT pk_app_settings PRIMARY KEY (setting_key)
);

CREATE VIEW sales.v_order_summary (order_id, customer_name, total_value) AS
  SELECT o.order_id, c.customer_name, SUM(l.quantity * l.unit_price)
  FROM sales.orders o
  JOIN sales.customer c ON c.customer_id = o.customer_id
  JOIN sales.order_line l ON l.order_id = o.order_id
  GROUP BY o.order_id, c.customer_name;

CREATE VIEW sales.v_employee_directory (emp_id, full_name, dept_name) AS
  SELECT e.emp_id, e.full_name, d.dept_name
  FROM sales.employee e
  JOIN sales.department d ON d.dept_id = e.dept_id;

CREATE VIEW sales.v_product_catalog (product_id, sku, product_name, unit_price) AS
  SELECT product_id, sku, product_name, unit_price FROM sales.product;

CREATE VIEW sales.v_audit_recent (log_id, message, created_at) AS
  SELECT log_id, message, created_at FROM sales.audit_log;
