/* sql-cartographer v3.1.0 — bundled demo sample SQL.
   (Role introduced v2.7.0; ERD schema samples moved here from src/erd.ts in
   v3.1.0 so algorithm modules stay free of data.)

   One representative script per dialect for the flowchart page's "Load sample"
   button, and two declared-constraint schemas for the erd.html sample buttons,
   so users can explore both analysers without preparing input. Kept as data,
   separate from the application controller. */
var SQL_CARTOGRAPHER_SAMPLES = {} as Record<Dialect, string>;
  SQL_CARTOGRAPHER_SAMPLES.tsql = [
"CREATE PROCEDURE dbo.usp_SyncStudentPhotos",
"    @SchoolYear INT,",
"    @DryRun BIT = 0",
"AS",
"BEGIN",
"    SET NOCOUNT ON;",
"    DECLARE @StudentId INT, @Processed INT = 0;",
"",
"    IF @SchoolYear IS NULL",
"    BEGIN",
"        RAISERROR('SchoolYear is required', 16, 1);",
"        RETURN -1;",
"    END",
"",
"    BEGIN TRY",
"        BEGIN TRANSACTION;",
"",
"        INSERT INTO dbo.PhotoSyncQueue (StudentId, QueuedUtc)",
"        SELECT s.StudentId, SYSUTCDATETIME()",
"        FROM dbo.Student s",
"        WHERE s.SchoolYear = @SchoolYear AND s.PhotoHash IS NULL;",
"",
"        DECLARE photo_cur CURSOR LOCAL FAST_FORWARD FOR",
"            SELECT StudentId FROM dbo.PhotoSyncQueue WHERE Processed = 0;",
"",
"        OPEN photo_cur;",
"        FETCH NEXT FROM photo_cur INTO @StudentId;",
"",
"        WHILE @@FETCH_STATUS = 0",
"        BEGIN",
"            IF @DryRun = 1",
"                PRINT 'Would sync ' + CAST(@StudentId AS VARCHAR(10));",
"            ELSE",
"            BEGIN",
"                EXEC dbo.usp_FetchPhotoFromWonde @StudentId;",
"                UPDATE dbo.Student SET PhotoHash = 0x00 WHERE StudentId = @StudentId;",
"                SET @Processed = @Processed + 1;",
"            END",
"",
"            IF @Processed > 5000 BREAK;",
"",
"            FETCH NEXT FROM photo_cur INTO @StudentId;",
"        END",
"",
"        CLOSE photo_cur;",
"        DEALLOCATE photo_cur;",
"        COMMIT TRANSACTION;",
"    END TRY",
"    BEGIN CATCH",
"        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;",
"        INSERT INTO dbo.SyncErrorLog (Proc, Message)",
"        VALUES ('usp_SyncStudentPhotos', ERROR_MESSAGE());",
"        THROW;",
"    END CATCH",
"",
"    SELECT @Processed AS Processed;",
"    RETURN 0;",
"END"].join('\n');

  SQL_CARTOGRAPHER_SAMPLES.db2 = [
"CREATE PROCEDURE ADMIN.SYNC_ENROLMENT (IN P_YEAR INTEGER, OUT P_COUNT INTEGER)",
"LANGUAGE SQL",
"SPECIFIC SYNC_ENROLMENT",
"BEGIN",
"    DECLARE V_ID INTEGER DEFAULT 0;",
"    DECLARE V_DONE SMALLINT DEFAULT 0;",
"",
"    DECLARE EXIT HANDLER FOR SQLEXCEPTION",
"    BEGIN",
"        ROLLBACK;",
"        RESIGNAL;",
"    END;",
"",
"    IF P_YEAR IS NULL THEN",
"        SET P_COUNT = 0;",
"    ELSEIF P_YEAR < 2000 THEN",
"        SIGNAL SQLSTATE '75001' SET MESSAGE_TEXT = 'Year too early';",
"    ELSE",
"        FOR row AS c1 CURSOR FOR",
"            SELECT ID FROM ADMIN.ENROLMENT WHERE SCHOOL_YEAR = P_YEAR",
"        DO",
"            UPDATE ADMIN.ENROLMENT SET SYNCED = 'Y' WHERE ID = row.ID;",
"            SET V_ID = V_ID + 1;",
"            IF V_ID > 10000 THEN",
"                LEAVE;",
"            END IF;",
"        END FOR;",
"",
"        CASE",
"            WHEN V_ID = 0 THEN CALL ADMIN.LOG_EMPTY(P_YEAR);",
"            WHEN V_ID > 5000 THEN CALL ADMIN.LOG_LARGE(V_ID);",
"            ELSE CALL ADMIN.LOG_OK(V_ID);",
"        END CASE;",
"",
"        SET P_COUNT = V_ID;",
"    END IF;",
"",
"    COMMIT;",
"    RETURN 0;",
"END"].join('\n');

  SQL_CARTOGRAPHER_SAMPLES.plpgsql = [
"CREATE OR REPLACE FUNCTION app.sync_students(p_year integer, p_dry_run boolean DEFAULT false)",
"RETURNS integer",
"LANGUAGE plpgsql",
"AS $$",
"DECLARE",
"    v_count integer := 0;",
"    r record;",
"BEGIN",
"    IF p_year IS NULL THEN",
"        RAISE EXCEPTION 'p_year is required';",
"    ELSIF p_year < 2000 THEN",
"        RETURN 0;",
"    END IF;",
"",
"    FOR r IN SELECT id FROM app.student WHERE school_year = p_year LOOP",
"        IF p_dry_run THEN",
"            RAISE NOTICE 'would sync %', r.id;",
"        ELSE",
"            PERFORM app.fetch_photo(r.id);",
"            UPDATE app.student SET photo_hash = NULL WHERE id = r.id;",
"        END IF;",
"",
"        v_count := v_count + 1;",
"        EXIT WHEN v_count > 5000;",
"    END LOOP;",
"",
"    BEGIN",
"        INSERT INTO app.sync_log (job, rows_done) VALUES ('photos', v_count);",
"    EXCEPTION",
"        WHEN unique_violation THEN",
"            RAISE NOTICE 'log entry already exists';",
"        WHEN others THEN",
"            RAISE;",
"    END;",
"",
"    RETURN v_count;",
"END;",
"$$;"].join('\n');

  SQL_CARTOGRAPHER_SAMPLES.sqlite = [
"CREATE TRIGGER trg_student_audit",
"AFTER UPDATE OF surname, given_name ON student",
"FOR EACH ROW",
"WHEN old.surname <> new.surname OR old.given_name <> new.given_name",
"BEGIN",
"    INSERT INTO audit (student_id, field, old_value, new_value, changed_at)",
"    VALUES (old.id, 'name', old.surname, new.surname, datetime('now'));",
"",
"    UPDATE student SET revision = revision + 1 WHERE id = old.id;",
"",
"    INSERT OR IGNORE INTO sync_queue (student_id) VALUES (old.id);",
"END;"].join('\n');

/* ===== ERD samples =====
   Schema DDL for the erd.html sample buttons. Declared constraints only, so
   the demo path shows exactly what the ERD will and will not assert. Used by
   the v2.1.0 fixtures so the demo path is covered by tests. */
var SQL_CARTOGRAPHER_ERD_SAMPLE_TSQL=[
  '/* Sample retail schema — declared constraints only. */',
  'CREATE TABLE dbo.Customer (',
  '  CustomerId  INT IDENTITY(1,1) PRIMARY KEY,',
  '  Email       NVARCHAR(200) NOT NULL UNIQUE,',
  '  DisplayName NVARCHAR(120) NOT NULL,',
  '  ReferredBy  INT NULL,',
  '  CONSTRAINT FK_Customer_Referrer FOREIGN KEY (ReferredBy)',
  '    REFERENCES dbo.Customer (CustomerId)',
  ');',
  'GO',
  'CREATE TABLE dbo.Product (',
  '  ProductId INT IDENTITY(1,1) PRIMARY KEY,',
  '  Sku       VARCHAR(40) NOT NULL,',
  '  UnitPrice DECIMAL(12,2) NOT NULL,',
  '  CONSTRAINT UQ_Product_Sku UNIQUE (Sku)',
  ');',
  'GO',
  'CREATE TABLE dbo.OrderHeader (',
  '  OrderId    INT IDENTITY(1,1) PRIMARY KEY,',
  '  CustomerId INT NOT NULL,',
  '  PlacedAt   DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME()),',
  '  Status     VARCHAR(20) NOT NULL,',
  '  CONSTRAINT FK_Order_Customer FOREIGN KEY (CustomerId)',
  '    REFERENCES dbo.Customer (CustomerId),',
  '  CONSTRAINT UQ_Order_Customer UNIQUE (CustomerId)',
  ');',
  'GO',
  'CREATE TABLE dbo.OrderLine (',
  '  OrderId   INT NOT NULL,',
  '  LineNo    INT NOT NULL,',
  '  ProductId INT NOT NULL,',
  '  Quantity  INT NOT NULL,',
  '  CONSTRAINT PK_OrderLine PRIMARY KEY (OrderId, LineNo),',
  '  CONSTRAINT FK_OrderLine_Order FOREIGN KEY (OrderId)',
  '    REFERENCES dbo.OrderHeader (OrderId),',
  '  CONSTRAINT FK_OrderLine_Product FOREIGN KEY (ProductId)',
  '    REFERENCES dbo.Product (ProductId) ON DELETE CASCADE',
  ');',
  'GO',
  'CREATE VIEW dbo.vOrderValue (OrderId, LineCount, TotalValue) AS',
  '  SELECT OrderId, COUNT(*), SUM(1) FROM dbo.OrderLine GROUP BY OrderId;'
].join('\n');

/* 8 tables, 4 views. EMPLOYEE (table 2) and ORDERS (table 4) are related
   through the employee who took the order. AUDIT_LOG and APP_SETTINGS are
   standalone: nothing references them and they reference nothing. */
var SQL_CARTOGRAPHER_ERD_SAMPLE_DB2=[
  '/* DB2 schema sample — declared constraints only. */',
  'CREATE SCHEMA sales;',
  '',
  'CREATE TABLE sales.department (',
  '  dept_id      INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 10),',
  '  dept_name    VARCHAR(80)   NOT NULL,',
  '  location     VARCHAR(80),',
  '  CONSTRAINT pk_department PRIMARY KEY (dept_id),',
  '  CONSTRAINT uq_department_name UNIQUE (dept_name)',
  ');',
  '',
  'CREATE TABLE sales.employee (',
  '  emp_id       INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY,',
  '  dept_id      INTEGER       NOT NULL,',
  '  manager_id   INTEGER,',
  '  full_name    CHARACTER VARYING(120) NOT NULL,',
  '  hired_on     DATE          NOT NULL DEFAULT CURRENT DATE,',
  '  salary       DECIMAL(11,2) NOT NULL,',
  '  CONSTRAINT pk_employee PRIMARY KEY (emp_id),',
  '  CONSTRAINT fk_employee_dept FOREIGN KEY (dept_id)',
  '    REFERENCES sales.department (dept_id) ON DELETE RESTRICT,',
  '  CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id)',
  '    REFERENCES sales.employee (emp_id) ON DELETE SET NULL',
  ');',
  '',
  'CREATE TABLE sales.customer (',
  '  customer_id  INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,',
  '  customer_name VARCHAR(120) NOT NULL,',
  '  email        VARCHAR(200)  NOT NULL,',
  '  country      CHAR(2),',
  '  CONSTRAINT pk_customer PRIMARY KEY (customer_id)',
  ');',
  '',
  'CREATE TABLE sales.orders (',
  '  order_id     INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,',
  '  customer_id  INTEGER       NOT NULL,',
  '  emp_id       INTEGER       NOT NULL,',
  '  order_date   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,',
  '  status       VARCHAR(20)   NOT NULL,',
  '  CONSTRAINT pk_orders PRIMARY KEY (order_id),',
  '  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)',
  '    REFERENCES sales.customer (customer_id) ON DELETE CASCADE,',
  '  CONSTRAINT fk_orders_employee FOREIGN KEY (emp_id)',
  '    REFERENCES sales.employee (emp_id) ON DELETE RESTRICT,',
  '  CONSTRAINT ck_orders_status CHECK (status IN (\'OPEN\',\'SHIPPED\',\'CANCELLED\'))',
  ');',
  '',
  'CREATE TABLE sales.product (',
  '  product_id   INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,',
  '  sku          VARCHAR(40)   NOT NULL,',
  '  product_name VARCHAR(160)  NOT NULL,',
  '  unit_price   DECIMAL(9,2)  NOT NULL,',
  '  CONSTRAINT pk_product PRIMARY KEY (product_id)',
  ');',
  'CREATE UNIQUE INDEX sales.uq_product_sku ON sales.product (sku);',
  '',
  'CREATE TABLE sales.order_line (',
  '  order_id     INTEGER       NOT NULL,',
  '  line_no      SMALLINT      NOT NULL,',
  '  product_id   INTEGER       NOT NULL,',
  '  quantity     INTEGER       NOT NULL,',
  '  unit_price   DECIMAL(9,2)  NOT NULL,',
  '  CONSTRAINT pk_order_line PRIMARY KEY (order_id, line_no),',
  '  CONSTRAINT fk_order_line_order FOREIGN KEY (order_id)',
  '    REFERENCES sales.orders (order_id) ON DELETE CASCADE,',
  '  CONSTRAINT fk_order_line_product FOREIGN KEY (product_id)',
  '    REFERENCES sales.product (product_id) ON DELETE RESTRICT',
  ');',
  '',
  '/* Standalone table 7: audit trail, no foreign keys in or out. */',
  'CREATE TABLE sales.audit_log (',
  '  log_id       BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY,',
  '  message      VARCHAR(500)  NOT NULL,',
  '  created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,',
  '  CONSTRAINT pk_audit_log PRIMARY KEY (log_id)',
  ');',
  '',
  '/* Standalone table 8: application settings, no foreign keys in or out. */',
  'CREATE TABLE sales.app_settings (',
  '  setting_key   VARCHAR(100) NOT NULL,',
  '  setting_value VARCHAR(500),',
  '  CONSTRAINT pk_app_settings PRIMARY KEY (setting_key)',
  ');',
  '',
  'CREATE VIEW sales.v_order_summary (order_id, customer_name, total_value) AS',
  '  SELECT o.order_id, c.customer_name, SUM(l.quantity * l.unit_price)',
  '  FROM sales.orders o',
  '  JOIN sales.customer c ON c.customer_id = o.customer_id',
  '  JOIN sales.order_line l ON l.order_id = o.order_id',
  '  GROUP BY o.order_id, c.customer_name;',
  '',
  'CREATE VIEW sales.v_employee_directory (emp_id, full_name, dept_name) AS',
  '  SELECT e.emp_id, e.full_name, d.dept_name',
  '  FROM sales.employee e',
  '  JOIN sales.department d ON d.dept_id = e.dept_id;',
  '',
  'CREATE VIEW sales.v_product_catalog (product_id, sku, product_name, unit_price) AS',
  '  SELECT product_id, sku, product_name, unit_price FROM sales.product;',
  '',
  'CREATE VIEW sales.v_audit_recent (log_id, message, created_at) AS',
  '  SELECT log_id, message, created_at FROM sales.audit_log;'
].join('\n');
